---
title: "Week 7 - Data File Types"
author: "Daniel Craig"
date: "2023-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(htmltools)
library(jsonlite)
library(XML)
library(RCurl)
library(methods)
```

# Introduction  
  
This week is focused on data file types that are commonly passed or retrieved when web scraping or dealing with APIs. This example will have an html, json, and xml file that I've hand created to get a better idea of each type of structure.  
  
Each file will include the authors, publisher, publishing date, and title of a different book related to data science.  

```{r}

html <- read_html("https://raw.githubusercontent.com/d-ev-craig/DATA607/main/Week%207%20-%20Web%20Data%20%26%20APIs/html2.html")

html

table <- html %>% html_element('.mytable') %>% html_table()

table
```
```{r JSON}

json <- jsonlite::fromJSON("https://raw.githubusercontent.com/d-ev-craig/DATA607/main/Week%207%20-%20Web%20Data%20%26%20APIs/json.json")


print(json$`Favorite Books`$Book1)
```

```{r XML}
xml <- getURL("https://raw.githubusercontent.com/d-ev-craig/DATA607/main/Week%207%20-%20Web%20Data%20%26%20APIs/xml.xml",ssl.verifyPeer = FALSE)

xml

xmlData <- xmlToDataFrame(xml)

print(xmlData)


```

